### PR TITLE
Jeffa/autocomplete js

### PR DESCRIPTION
**Pull request by Ninjef**
Found a much easier solution than building it myself (though I was THIS close to being done, and it was a great learning experience): http://api.jqueryui.com/autocomplete

This works on /transactions/new for both cause and retailer

### CODE REVIEW

**Comment by blainehowerton** [comment]
The dropdown for user on the transaction form doesn't seem to be saving a value.  Do you have a quick fix?

**Comment by blainehowerton** [comment]
Jeff, don't worry about the dropdown for the user form...  I got it fixed in my devise branch.  When I merge it should fix the view and save problems because I was able to set the controller to save the logged in username automatically (without user input) to the transaction.  I have more work to do before I merge though.

**Comment by blainehowerton** [comment]
Jeff,

When I merged the typeahead in git - it is typing ahead all items in both tables (causes and retailers).  Can you take a look before I merge transaction-view and let me know what happened (so I have future reference)?

**Comment by blainehowerton** [comment]
Jeff,

Actually, it seems to be working after a browser refresh.  Can you take a final look before I merge in transaction-view?  All of this merging makes me nervous.  :)

B

**Comment by Ninjef** [comment]
I'm taking a look at it now, but it's insanely big... +12,566 new lines of
code over 31 files... what exactly is this supposed to be doing?

**Comment by Ninjef** [comment]
So yeah, it'll help me a lot if you could describe what features/functions
the PR is adding/subtracting. Otherwise I'm not really sure what I'm
looking at lol.

Thanks!
-Jeff

**Comment by blainehowerton** [comment]
Jeff,

The origin branch has your updates with the typeahead and a bit of my work
with devise.  In a few instances, I have had times where I added something
in my branch and it went on to origin anyways... I think it had to do with
my tracking in git.  I'm pretty sure I got that straightened out (it seems
to be working fine now).  It was a bit frustrating (and probably a result
of me working on it at that particular time when my mind wasn't completely
fresh).

So, while adding devise functionality it creates a bunch of template
views... this is a large part of the file additions you are seeing.  I will
delete these views (and lines of code) as I determine they are not needed.
I didn't want to mess with the origin branch now though until we had your
updates in an acceptable state.

And any advice you can give me on the transactionview merge errors would be
great.

[image: photo]
_Blaine Howerton_
Denver Media Center LLC
Yellow Gal High Definition LLC
3853 S Broadway | Englewood, CO  | 80113
t: 720-255-1640 xt 101
e: bhowerton@yghdtv.com
w: http://DenverMediaCenter.com http://denvermediacenter.com
http://yghdtv.com
https://tracking.cirrusinsight.com/3a49e13f-7d27-4272-981a-c309bdd1ca51/facebook-com-denvermediacenter

https://tracking.cirrusinsight.com/3a49e13f-7d27-4272-981a-c309bdd1ca51/twitter-com-yghdtv

https://tracking.cirrusinsight.com/3a49e13f-7d27-4272-981a-c309bdd1ca51/linkedin-com-in-blainehowerton

**Comment by Ninjef** [comment]
Blaine,
Sorry it's been so long. We had my in laws stay with us this weekend and
had an awesome time with them.

I haven't had time to look at the merge errors, but I can tell you how to
fix those:
Attempt to merge master into your branch by going to your branch in the
command line and executing:
git merge master
then you will see a list of conflicts. Go into your editor (if you haven't
gotten it already, I would recommend sublime text) and find the files which
have conflicts. In those files, you will see notation indicating the
conflicts which are arising. it will be something like:
<<<<<<<< YOUR BRANCH

# code that does A

code that does B
<<<<<<<< OTHER BRANCH

Then all you have to do is pick which code you want to keep, and delete
everything else (delete "<<<<<<< YOUR BRANCH", "================", the code
you don't want to keep, and "<<<<<<<<<< OTHER BRANCH")

I will take a look at the other problem as soon as I can.

Also, we have yet to figure out how to get the images up to amazon (AWS),
correct? Are you sure you want to add devise into the mix before we've
figured that out? (Nick told me we CAN upload the images into our database,
but we need to keep in mind that doing so will cause our database to fill
up FAST, especially if we're not reducing the image size every time we do
so, so we're probably going to run into huge problems potentially very
quickly if we don't get AWS images working).

-Jeff

**Pull request merged**
