### PR TITLE
Jeffa/seeds

### PR DESCRIPTION
**Pull request by Ninjef**
Just some seeds that will help creating queries for reports.

The transactions seeds don't work on my computer... I get problems with imagemagic and paperclip. All the more reason we should switch to storing this stuff on AWS so all we have to store is a url.

The errors I get are:

```
ActiveRecord::SchemaMigration Load (1.0ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-8encwe.jpg'
Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-a1vx3h.jpg[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-a1vx3h.jpg[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
   (0.3ms)  BEGIN
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-17z2wft.jpg'
   (0.3ms)  ROLLBACK
```

### CODE REVIEW

**Comment by blainehowerton** [comment]
Jeff

The images are stored in aws and they should upload when you do your setup
(i set the seeds to upload a sample image in the project to aws via paper
clip). I'm not sure why this isn't working for you - it worked for both
heroku and my local when I deleted the database and set up from scratch.

I think the transactions problem you are having are probably related to the
upload of the image to aws. It requires an image for the controller to
operate. the errors appear to say that it can't find the image on the
server. I did delete a bunch of images last night on the aws server. It's
possible that if you did this yesterday before I did that, than I
inadvertently deleted those images.

Blaine

**Comment by blainehowerton** [comment]
Jeff

Are you sure your local is in the master branch on my digin rewards git
hub? Are you somehow downloading from ninjef? I'm updating the master
branch on my account (not yours).
On Sat, Apr 16, 2016 at 11:20 AM Blaine Howerton bhowerton@yghdtv.com
wrote:

> Jeff
> 
> The images are stored in aws and they should upload when you do your setup
> (i set the seeds to upload a sample image in the project to aws via paper
> clip). I'm not sure why this isn't working for you - it worked for both
> heroku and my local when I deleted the database and set up from scratch.
> 
> I think the transactions problem you are having are probably related to
> the upload of the image to aws. It requires an image for the controller to
> operate. the errors appear to say that it can't find the image on the
> server. I did delete a bunch of images last night on the aws server. It's
> possible that if you did this yesterday before I did that, than I
> inadvertently deleted those images.
> 
> Blaine
> 
> On Sat, Apr 16, 2016 at 10:57 AM Ninjef notifications@github.com wrote:
> 
> > Just some seeds that will help creating queries for reports.
> > 
> > The transactions seeds don't work on my computer... I get problems with
> > imagemagic and paperclip. All the more reason we should switch to storing
> > this stuff on AWS so all we have to store is a url.
> > 
> > The errors I get are:
> > 
> > ActiveRecord::SchemaMigration Load (1.0ms)  SELECT "schema_migrations".\* FROM "schema_migrations"
> > Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-8encwe.jpg'
> > Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-a1vx3h.jpg[0]' 2>/dev/null
> > [paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
> > Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-a1vx3h.jpg[0]' 2>/dev/null
> > [paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
> >    (0.3ms)  BEGIN
> > Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/x8/l99jyg_x3hj73gd6b193h7ddn2d567/T/45053265723f59bd84cf4af2b15def8e20160416-57019-17z2wft.jpg'
> >    (0.3ms)  ROLLBACK
> > 
> > ---
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> >   https://github.com/blainehowerton/diginrewards/pull/14
> > Commit Summary
> > - backed up local database for future population of data
> > - collapsed migrations and created a starting structure
> > - new db seeds for creating reports
> > 
> > File Changes
> > - _D_ database.bak
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-0
> >   (0)
> > - _D_ db/migrate/20160330190101_create_structure.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-1
> >   (97)
> > - _D_ db/migrate/20160401004058_retailer_split_fields.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-2
> >   (7)
> > - _D_ db/migrate/20160404081714_create_rewards_transactions.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-3
> >   (14)
> > - _D_ db/migrate/20160404081729_create_retailer_transactions.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-4
> >   (16)
> > - _D_ db/migrate/20160404081745_create_cause_transactions.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-5
> >   (16)
> > - _D_ db/migrate/20160404090214_create_user_transactions.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-6
> >   (19)
> > - _D_ db/migrate/20160404155111_revise_transactions_table.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-7
> >   (7)
> > - _D_ db/migrate/20160411160201_add_field_to_rewards_transactions.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-8
> >   (5)
> > - _A_ db/migrate/20160411160201_create_structure.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-9
> >   (6)
> > - _M_ db/seeds.rb
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-10
> >   (64)
> > - _A_ dig_development.bak
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-11
> >   (0)
> > - _D_ dig_development.sql
> >   https://github.com/blainehowerton/diginrewards/pull/14/files#diff-12
> >   (190)
> > 
> > Patch Links:
> > - https://github.com/blainehowerton/diginrewards/pull/14.patch
> > - https://github.com/blainehowerton/diginrewards/pull/14.diff
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/blainehowerton/diginrewards/pull/14
> > 
> > ## 
> > 
> > Blaine Howerton
> > Denver Media Center
> > Yellow Gal High Definition
> > 720.255.1640 xt 101

## 

Blaine Howerton
Denver Media Center
Yellow Gal High Definition
720.255.1640 xt 101

**Comment by Ninjef** [comment]
Yeah, I'm using the right repo and branch. Just a little confused as to how
the images thing works. Was expecting to be able to simply provide a url to
the image, but it looked like I had to provide a local image, & the "image"
field led me to believe the whole image was being stored _there_. Sorry for
the confusion.

**Comment by blainehowerton** [comment]
Oh. I see what you are saying now... For the report you want to save the
value of the image.... You should be able to pull that to your object by
calling transaction.image correct?

**Comment by Ninjef** [comment]
No, definitely don't want to do that. I was simply trying to create good seed data for my dev work and all our future dev work. But the transactions seeds were failing due to some weird error between paperclip and imagemagic. I was expecting to be able to do:
`Transaction.create(amount: '100.00', user_id: '1', image_url: 'http://psychosmology.com/wp-content/uploads/2015/08/Snakes-4.jpg', retailer_id: '1', transaction_date: 'April 05, 2016', cause_split: '.03', retailer_split: '.03', fee_split: '.09', cause_id: '1', status: 'Final')`

But There was no url field that I could find.

**Comment by blainehowerton** [comment]
Ahh I see what you're trying to do now.  I worked through this a few nights
ago.  Paperclip needs a local image to upload to the server (because it
assigns a directory structure on AWS based on the transaction.id number).
The seed argument below for a transaction works.  Note the "image" variable
and method call.  It needs to create a "new" (File.new) image by copying an
existing image (reptiles.jpg in this case) over to the AWS server.  I
believe it then creates an image_url and saves it in
transactions.image_file_name (or potentially transactions.image, I'm not
sure though)

One of the seeds:
Transaction.create(amount: '100.00', user_id: '1', image:
File.new("public/images/reptiles.jpg"), retailer_id: '1', transaction_date:
'April 05, 2016', cause_split: '.03', retailer_split: '.03', fee_split:
'.09', cause_id: '1', status: 'Final')

Rails_admin doesn't let me see the image_url, but it should be something
like (
http://s3-us-west-2.amazonaws.com/diginrewards/transactions/images/000/000/002/thumb/reptiles.jpg?1460754638)
for each image it uploads.  BTW, for each image it actually re-creates 2
images and uploads the original to AWS (a small, medium, and large).  It
does this for thumbnails, medium sized display, and original file.  This
value should be able to be pulled from the transaction.image_file_name
field in an object for the transaction (but I'm not completely sure about
that).

[image: photo]
_Blaine Howerton_
Denver Media Center LLC
Yellow Gal High Definition LLC
3853 S Broadway | Englewood, CO  | 80113
t: 720-255-1640 xt 101
e: bhowerton@yghdtv.com
w: http://DenverMediaCenter.com http://denvermediacenter.com
http://yghdtv.com
http://facebook.com/denvermediacenter  http://twitter.com/yghdtv
http://www.linkedin.com/in/blainehowerton

**Comment by Ninjef** [comment]
I was originally trying that:
`Transaction.create(amount: '100.00', user_id: '1', image:
File.new("public/images/reptiles.jpg"), retailer_id: '1', transaction_date:
'April 05, 2016', cause_split: '.03', retailer_split: '.03', fee_split:
'.09', cause_id: '1', status: 'Final')`
And it was breaking (that's what the errors in my first post on this page are from), so I was wishing and hoping that there was an easier way (ie. just setting the url to the image and being done with it) :-\

**Comment by Ninjef** [comment]
Don't worry about this though, Blaine. I don't think I even need transaction records in the db to do the work you guys want me to do, so it's fine.

I'll try and figure out the issue some day if I have time ;-)

**Comment by blainehowerton** [comment]
Sounds good.  As we add things like this we will get more familiar with the
way Paperclip does its magic.  I really do like the gem.

[image: photo]
_Blaine Howerton_
Denver Media Center LLC
Yellow Gal High Definition LLC
3853 S Broadway | Englewood, CO  | 80113
t: 720-255-1640 xt 101
e: bhowerton@yghdtv.com
w: http://DenverMediaCenter.com http://denvermediacenter.com
http://yghdtv.com
http://facebook.com/denvermediacenter  http://twitter.com/yghdtv
http://www.linkedin.com/in/blainehowerton

**Pull request merged**
